name: ztfsummer
channels:
  - conda-forge
  - astropy
  - pytorch
  - defaults
dependencies:
  - _tflow_select=2.3.0=eigen
  - absl-py=0.13.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38h294d835_0
  - argon2-cffi=20.1.0=py38h294d835_2
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.111=mkl
  - blas-devel=3.9.0=11_win64_mkl
  - bleach=4.0.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h294d835_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30=py38haa244fe_0
  - cffi=1.14.6=py38hd8c33c5_0
  - chardet=4.0.0=py38haa244fe_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38haa244fe_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py38hd7da0ea_0
  - cudatoolkit=11.1.1=heb2d755_7
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.4.1=py38h885f38d_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h546665d_1
  - gast=0.4.0=pyh9f0ad1d_0
  - google-auth=1.34.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.38.1=py38he5377a8_0
  - h5py=2.10.0=nompi_py38he6c2248_106
  - hdf5=1.10.6=nompi_h5268f04_1114
  - icu=68.1=h0e60522_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.4=py38haa244fe_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - ipykernel=6.1.0=py38h595d716_0
  - ipython=7.26.0=py38h595d716_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.0=py38haa244fe_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38haa244fe_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38haa244fe_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38hbd9d945_1
  - krb5=1.19.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.78.0=h789b8ee_0
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=11_win64_mkl
  - liblapacke=3.9.0=11_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.17.2=h7755175_1
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.3.0=h0c97f57_1
  - libuv=1.42.0=h8ffe710_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h294d835_0
  - matplotlib-base=3.4.3=py38h1f000d6_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py38h294d835_1004
  - mkl=2021.3.0=hb70f87d_564
  - mkl-devel=2021.3.0=h57928b3_565
  - mkl-include=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py38h294d835_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38haa244fe_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h5362a0b_0
  - notebook=6.4.3=pyha770c72_0
  - numpy=1.21.1=py38h09042cb_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h8ffe710_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.1=py38h60cbd38_0
  - pandoc=2.14.1=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py38h794f750_0
  - pip=21.0.1=py38haa95532_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - prompt_toolkit=3.0.19=hd8ed1ab_0
  - protobuf=3.17.2=py38h885f38d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38haa244fe_7
  - pyqt-impl=5.12.3=py38h885f38d_7
  - pyqt5-sip=4.19.18=py38h885f38d_7
  - pyqtchart=5.12=py38h885f38d_7
  - pyqtwebengine=5.12.1=py38h885f38d_7
  - pyreadline=2.1=py38haa244fe_1003
  - pyrsistent=0.17.3=py38h294d835_2
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.11=h6244533_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32=301=py38h294d835_0
  - pywinpty=0.5.7=py38_0
  - pyzmq=22.2.1=py38h09162b1_0
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scipy=1.7.1=py38ha1292f7_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h2bbff1b_0
  - statsmodels=0.12.2=py38h347fdf6_0
  - tbb=2021.3.0=h2d74725_0
  - tensorboard=2.6.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py38haa244fe_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.3.0=mkl_py38h8c0d9a2_0
  - tensorflow-base=2.3.0=eigen_py38h75a453f_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py38h294d835_1
  - traitlets=5.0.5=py_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38haa244fe_4
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38h294d835_3
  - xz=5.2.5=h62dcd97_1
  - yarl=1.6.3=py38h294d835_2
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
prefix: C:\Users\ecoughlin\Miniconda3\envs\ztfsummer
